### ISSUE TITLE
UserService BasicProfile

### ISSUE THREAD

**Issue by dispalt** [jaliss/securesocial#411]
Why does the UserService[U] use BasicProfile in some of the functions vs GenericProfile.  Right now I have to transmutate between BasicProfile and my user class.  Is there a specific reason? I am on master, thanks!

**Comment by gicmo** [comment]
Being bit by this issue while trying to upgrade to play 2.3. Thought about fixing it myself when I realised that there is already pr #477 that addresses this issue. Sadly the pr also has lots of formatting changes too and has unresolved merge conflicts.

**Comment by zorbalaras** [comment]
I have to move away of 2.1.3 due to localization issue fixed in: "Fixed i18n issues: API breaking changes in TemplatesPlugin, PasswordValidator and templates". Migrating to 3.0, I am facing this migration issue (I am using Java). I plan to step-back and build a patched version of 2.1.3... Any better suggestion would be very welcome :-)

**Comment by sdk451** [comment]
Have to agree the majority of posters abut this. Currently persisting tokens and userprofiles requires a wrapper or mixin class (one's own implementation of Profile) around BasicProfile for the override implementation of UserService. It would be far easier to use the GenericProfle interface and have BasicProfile as a default implementation, allowing users to implement GenericProfile in their own UserProfile subclass. The problem in the pattern is that the methods in UserService.scala return Future[Option[BasicProfile]] instead of Future[Option[GenericProfile]]. I believe there is a pull request (#477?) to change this. Anything happen with that?
