### ISSUE TITLE
What is the current recommended Secure Social version to use in build.sbt?

### ISSUE THREAD

**Issue by pkarjala** [jaliss/securesocial#547]
I am attempting to set up SecureSocial in Play 2.3.7, and the following methods in my build.sbt file return problems with being able to find the correct repository for the plugin, as directed at http://securesocial.ws/guide/installation.html

`"ws.securesocial" %% "securesocial" % "2.1.4"`

Nothing is found.

I was able to locate a specific path at http://www.mvnrepository.com/artifact/ws.securesocial/securesocial_2.10/2.1.4 by clicking on the SBT tab, which provided:

`libraryDependencies += "ws.securesocial" % "securesocial_2.10" % "2.1.4"`

Is 2.1.4 still the preferred version to use against Play 2.3.7, or is it better to use one of the 3.0 releases?  Also, what is the difference between securesocial_2.10 and securesocial_2.11 at http://www.mvnrepository.com/artifact/ws.securesocial?

**Comment by xianminx** [comment]
Appendix `2.10` and `2.11`  of `securesocial_2.10` denotes the scala version respectively. 

If you use scala `2.11`, only `3.0` version of SecureSocial is provided, as per page http://www.mvnrepository.com/artifact/ws.securesocial/securesocial_2.11 illustrates. 
so, use 

```
"ws.securesocial" %% "securesocial" % "3.0-M3"
```

instead in your build.sbt.

**Comment by xianminx** [comment]
Appendix `2.10` and `2.11`  of `securesocial_2.10` denotes the scala version respectively. 

If you use scala `2.11`, only `3.0` version of SecureSocial is provided, as per page http://www.mvnrepository.com/artifact/ws.securesocial/securesocial_2.11 illustrates. 
so, use 

```
"ws.securesocial" %% "securesocial" % "3.0-M3"
```

instead in your build.sbt.

Or, since SecureSocial 3.0 is not stable, if you prefer to use stable SecureSocial 2.1.4, you can use the specified version: 

```
"ws.securesocial" % "securesocial_2.10" % "2.1.4"
```

checkout http://www.scala-sbt.org/0.13/tutorial/Library-Dependencies.html#Getting+the+right+Scala+version+with for differences between single `%`  and double `%%`

> If you use groupID %% artifactID % revision rather than groupID % artifactID % revision (the difference is the double %% after the groupID), sbt will add your project’s Scala version to the artifact name. This is just a shortcut. You could write this without the %%:
