### ISSUE TITLE
UserNamePassword authentication should be case sensitive

### ISSUE THREAD

**Issue by albertostratio** [jaliss/securesocial#561]
Currently the doAuthentication method in UserNamePassword class is transforming the userid to lowercase:

```
credentials => {
        val userId = credentials._1.toLowerCase
        val password = credentials._2
```
If you are working with databases which care of lower and upper case (for instance PostgreSQL) the auth method will not work properly

**Comment by brianwawok** [comment]
@albertostratio seems like a flaw in your design... a user should NOT need to remember if he logged in to your site as "billybob42" or "BillyBob42" or "BILLYBOB42"..     just pick a case (upper or lower), and store all usernames in that case

**Comment by jaliss** [comment]
I agree with @brianwawok.  Unless there's a really good reason I don't see why we would need them to be case sensitive.

**Comment by jaliss** [comment]
Closing this for now. Please re-open if needed.

**Comment by AndriusA** [comment]
Currently userId is handled inconsistently: userId is not transformed to lowerCase when withUserNameSupport is enabled:

https://github.com/jaliss/securesocial/blob/a00198e496d0a87f9b136666d99a72f3a0b5eed8/module-code/app/securesocial/controllers/Registration.scala#L167

Resulting in a situation where nobody with non-lowercase username is able to login because userId is transformed to lowerCase when logging in.
